/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
export {}
declare global {
  const ALQkvq: typeof import('@arco-design/web-vue')['LQkvq']
  const AMUCAX: typeof import('@arco-design/web-vue')['MUCAX']
}
